### ISSUE TITLE
Possible mistakes in the info??

### ISSUE THREAD

**Issue by baltcoinh** [kokleong98/aura-setup#1]
Hi,
I have been configuring your script to use in my aura node (good work) but I think a change should be done to the crontab to work flawlessly:
SHELL=/home/<myusername>/cron.bash
should be??
SHELL=/home/<myusername>/aura.bash

**Comment by kokleong98** [comment]
Hi baltcoinh,
You definitely hit the bull eyes. 
Thank you for feedback.
I have updated the documentation.
