### ISSUE TITLE
Email send problem

### ISSUE THREAD

**Issue by Ernestopheles** [kokleong98/aura-setup#2]
Having installed "aura cron staking offline monitoring setup" - Working fine

Having done "add email notification on staking offline restart" but did not use postfix but ssmtp 
- get: 
` sSMTP[22326]: Creating SSL connection to host
 sSMTP[22326]: SSL connection using ECDHE_RSA_AES_256_GCM_SHA384
 cron[508]: sendmail: 550 Sender address is not allowed.
 sSMTP[22326]: 550 Sender address is not allowed.
`
Running mon_actions.sh in Terminal works fine. 

After hours of trial my Emailaccount had been blocked for one day, mailbox unavailable.

Testing the following in crontab -e under my user:
SHELL=/home/.../aura.bash
#*/1 * * * * /home/.../mon_actions.sh # Error: sSMTP[12353]: 550 Sender address is not allowed.

Trying to workaround:
#*/1 * * * *  ssmtp ...@web.de #working, empty email
#*/1 * * * * /home/.../mon_actions.sh | ssmtp ...@web.de #working, output of script not in email (empty)
#*/1 * * * * /home/.../mon_actions.sh > ssmtp ...web.de #not sending any email
#*/1 * * * *  ssmtp ...@web.de < /home/.../mon_actions.sh #working, code of script in email 
#*/1 * * * *  ssmtp ...@web.de < "Test" #Error: Sender address not allowed

**Comment by kokleong98** [comment]
Hi Ernestopheles,
Currently my script only work on specific mailing component. (Postfix and mailutils)
You may try "configure mail service" section which come with a configure email script. I highly recommend you create a new Gmail account for app mailing purpose to avoid security and mail account locking problem.

**Comment by Ernestopheles** [comment]
#/1 * * * * /home/.../mon_actions.sh | ssmtp ...@web.de 

This is working, output of script is not in email body (empty), but can be seen in "source text" (extended header) of email. 

So at least got it working that way. Thank you for your solution and support.

**Comment by Ernestopheles** [comment]
Not solved yet, as each time cron starts the script an email will be sent Even if Staking Online.

**Comment by kokleong98** [comment]
Let me try it tonight. That's script is my earliest solution. Possible some unknown bug that I didn't discover.

**Comment by kokleong98** [comment]
Hi, Ernestopheles.

I have change script to check "aura status" instead of "aura logs". Now I think it should meet your expectation.

Take note also do not make the cron job frequency too short, because you aura status might be still offline when trying sync. The best is to use my systemd solution.

**Comment by Ernestopheles** [comment]
Hi SOO,
Thanks for caring. But I do not think your changes have anything to do with my problem, as your changes affect only the conditional statements, which had been working well before.
The problem is, that the mail system (ssmtp) refuses to send email (invalid sender) if initiated by the usual behaviour of cron (output of command not empty).
Thats why I tried the workarounds (in crontab pipe to ssmtp). Which does not help, as even if script has not output (everything is running fine) emails will be sent. So I would have to open the extended header of each email to see if aura-staking is offline or not.  

I have tried notification by email several times now, using crontab or logcheck, all of which were unsatiesfying. Probably I am yet not deep enough in Linux (I grew up with MSDOS and later windows, Linux is quite fresh.)

Thank you anyway.

**Comment by kokleong98** [comment]
Hi Ernestopheles,

If your problem not with my script, maybe you should modify my script and or create one single script instead of piping from the crontab.

Secondly, maybe you should consider install and use Postfix and mailutils component. It can use SSAL to communicate with public mail server instead your own mail server.

I'm not sure whether that advice is helpful or not. Or you may share your solution details here.

**Comment by kokleong98** [comment]
Hi Ernestopheles,

I will close this issue since this is nothing related to repository or anything need to be fix.
